Regenerated.

diff --git a/modules/syscalls/configure b/modules/syscalls/configure
--- a/modules/syscalls/configure
+++ b/modules/syscalls/configure
@@ -3639,8 +3639,7 @@ fi
 
 
 
-
-for ac_func in erf erfc lgamma lgamma_r fstatvfs statvfs
+for ac_func in erf erfc lgamma fstatvfs statvfs
 do
 as_ac_var=`echo "ac_cv_func_$ac_func" | $as_tr_sh`
 echo "$as_me:$LINENO: checking for $ac_func" >&5
@@ -3740,6 +3739,79 @@ _ACEOF
 
 fi
 done
+
+echo "$as_me:$LINENO: checking whether lgamma_r is declared" >&5
+echo $ECHO_N "checking whether lgamma_r is declared... $ECHO_C" >&6
+if test "${ac_cv_have_decl_lgamma_r+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <math.h>
+
+int
+main ()
+{
+#ifndef lgamma_r
+  char *p = (char *) lgamma_r;
+#endif
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_have_decl_lgamma_r=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_have_decl_lgamma_r=no
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
+echo "$as_me:$LINENO: result: $ac_cv_have_decl_lgamma_r" >&5
+echo "${ECHO_T}$ac_cv_have_decl_lgamma_r" >&6
+if test $ac_cv_have_decl_lgamma_r = yes; then
+
+cat >>confdefs.h <<_ACEOF
+#define HAVE_DECL_LGAMMA_R 1
+_ACEOF
+
+
+else
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_DECL_LGAMMA_R 0
+_ACEOF
+
+
+fi
+
 
 echo "$as_me:$LINENO: checking whether signgam is declared" >&5
 echo $ECHO_N "checking whether signgam is declared... $ECHO_C" >&6
