regenerated

diff --git a/modules/syscalls/configure b/modules/syscalls/configure
--- a/modules/syscalls/configure
+++ b/modules/syscalls/configure
@@ -4704,7 +4704,8 @@ fi
 
 
 
-for ac_func in clock confstr fcntl gethostent sysconf uname getlogin getpwent getpwnam getpwuid getuid openlog setlogmask syslog closelog getpgid setpgrp getsid setsid kill endutxent getutxent getutxid getutxline pututxline setutxent fchmod fchown fstat link stat symlink utime mknod chmod umask
+
+for ac_func in clock confstr fcntl gethostent sysconf uname getlogin getpwent getpwnam getpwuid getuid openlog setlogmask syslog closelog getpgid setpgrp getsid setpgid setsid kill endutxent getutxent getutxid getutxline pututxline setutxent fchmod fchown fstat link stat symlink utime mknod chmod umask
 do
 as_ac_var=`echo "ac_cv_func_$ac_func" | $as_tr_sh`
 echo "$as_me:$LINENO: checking for $ac_func" >&5
@@ -6127,6 +6128,74 @@ _ACEOF
   fi
 fi
 
+if test "$ac_cv_func_setpgrp" = "yes"; then
+echo "$as_me:$LINENO: checking whether setpgrp() is POSIX" >&5
+echo $ECHO_N "checking whether setpgrp() is POSIX... $ECHO_C" >&6
+if test "${ac_cv_func_setpgrp_posix+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+#ifdef HAVE_UNISTD_H
+#include <unistd.h>
+#endif
+#include <sys/types.h>
+
+int
+main ()
+{
+pid_t pid = setpgrp();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_func_setpgrp_posix=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_func_setpgrp_posix=no
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
+echo "$as_me:$LINENO: result: $ac_cv_func_setpgrp_posix" >&5
+echo "${ECHO_T}$ac_cv_func_setpgrp_posix" >&6
+if test "$ac_cv_func_setpgrp_posix" = "yes"; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_SETPGRP_POSIX 1
+_ACEOF
+
+fi
+fi
 
 { echo "$as_me:$LINENO:  * System Calls (output)" >&5
 echo "$as_me:  * System Calls (output)" >&6;}
