regenerated

diff --git a/modules/rawsock/configure b/modules/rawsock/configure
--- a/modules/rawsock/configure
+++ b/modules/rawsock/configure
@@ -2736,8 +2736,10 @@ done
 
 
 
+
+
 for ac_header in sys/socket.h netinet/in.h arpa/inet.h linux/if_packet.h \
-                  sys/ioctl.h errno.h stropts.h poll.h sys/un.h
+   sys/ioctl.h errno.h stropts.h poll.h sys/un.h winsock2.h ws2tcpip.h
 do
 as_ac_Header=`echo "ac_cv_header_$ac_header" | $as_tr_sh`
 if eval "test \"\${$as_ac_Header+set}\" = set"; then
@@ -3022,7 +3024,62 @@ done
 
 { echo "$as_me:$LINENO: * RAWSOCK (Functions):" >&5
 echo "$as_me: * RAWSOCK (Functions):" >&6;}
-echo "$as_me:$LINENO: checking for library containing socket" >&5
+if test "$ac_cv_header_winsock2_h" = "yes"; then
+        echo "$as_me:$LINENO: checking for socket() in ws2_32" >&5
+echo $ECHO_N "checking for socket() in ws2_32... $ECHO_C" >&6
+  LIBS=${LIBS}' -lws2_32';
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <winsock2.h>
+int
+main ()
+{
+socket(0,0,0)
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_search_socket=yes
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_search_socket=no
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+else
+  echo "$as_me:$LINENO: checking for library containing socket" >&5
 echo $ECHO_N "checking for library containing socket... $ECHO_C" >&6
 if test "${ac_cv_search_socket+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -3148,13 +3205,19 @@ if test "$ac_cv_search_socket" != no; then
 
 fi
 
+fi
 if test "$ac_cv_search_socket" = "no"; then
-  { { echo "$as_me:$LINENO: error: cannot find SOCKET library" >&5
-echo "$as_me: error: cannot find SOCKET library" >&2;}
+  { { echo "$as_me:$LINENO: error: cannot find SOCKET library
+See \`config.log' for more details." >&5
+echo "$as_me: error: cannot find SOCKET library
+See \`config.log' for more details." >&2;}
    { (exit 1); exit 1; }; }
 fi
 
-for ac_func in poll
+
+
+
+for ac_func in poll socketpair recvmsg sendmsg
 do
 as_ac_var=`echo "ac_cv_func_$ac_func" | $as_tr_sh`
 echo "$as_me:$LINENO: checking for $ac_func" >&5
