fix 2010-07-09 ${DESTDIR} patch which broke "make install DESTDIR=...": only respect DESTDIR in "install", not in "add" mode * src/clisp-link.in (try_set_LIBDIR): extract from ... (set_dynamic_module_location): use try_set_LIBDIR; accept DESTDIR as an argument (prepare_dynamic_module): accept DESTDIR as an argument (add): pass "" as the DESTDIR to prepare_dynamic_module (install): pass DESTDIR as DESTDIR to prepare_dynamic_module

diff --git a/src/clisp-link.in b/src/clisp-link.in
--- a/src/clisp-link.in
+++ b/src/clisp-link.in
@@ -143,22 +143,25 @@ clisp_eval() {
 # Where do we install?
 DYNMOD="dynmod"              # should be in sync with defs1.lisp:require
 LIBDIR=""
+try_set_LIBDIR() {
+  mkdir -p "$1" || fail "Directory $2=$1 does not exist"
+  mkdir -p "$1/${DYNMOD}" || fail "Directory $2=$1 is not writable"
+  f="$1/${DYNMOD}/.abazonk"
+  if touch "$f" 2>/dev/null; then
+    rm -f "$f"
+    LIBDIR=$1
+  fi
+}
 set_dynamic_module_location() {
   if test -z "${LIBDIR}"; then
-    if touch "${DESTDIR}${CLISP_LIBDIR}/${DYNMOD}/.abazonk" 2>/dev/null; then
-      rm -f "${DESTDIR}${CLISP_LIBDIR}/${DYNMOD}/.abazonk"
-      LIBDIR=${CLISP_LIBDIR}
-    else # cf. src/m4/clisp.m4
+    DESTDIR="$1"
+    try_set_LIBDIR "${DESTDIR}${CLISP_LIBDIR}" "*lib-directory*"
+    if test -z "${LIBDIR}"; then # cf. src/m4/clisp.m4
       CLISP_LIBDIR_USER=`clisp_eval '(and *user-lib-directory* (namestring *user-lib-directory*))'`
       test "${CLISP_LIBDIR_USER}" = "NIL" && \
         fail "Cannot determine the dynamic module directory: *lib-directory* is not writable and *user-lib-directory* is not specified"
-      mkdir -p ${CLISP_LIBDIR_USER}/${DYNMOD} || \
-        fail "Cannot write in *user-lib-directory*"
-      if touch ${CLISP_LIBDIR_USER}/${DYNMOD}/.abazonk 2>/dev/null; then
-        rm -f ${CLISP_LIBDIR_USER}/${DYNMOD}/.abazonk
-        LIBDIR=${CLISP_LIBDIR_USER}
-      else fail "Cannot determine the dynamic module directory: neither *lib-directory* nor *user-lib-directory* are writable"
-      fi
+      try_set_LIBDIR "${CLISP_LIBDIR_USER}" "*user-lib-directory*"
+      test -z "${LIBDIR}" && fail "Cannot determine the dynamic module directory: neither *lib-directory* nor *user-lib-directory* are writable"
     fi
   fi
 }
@@ -179,7 +182,8 @@ with_dynamic_modules=${with_dynamic_modules-@with_dynamic_modules@}
 #   ${absolute_currentdir} : the top level directory
 prepare_dynamic_module() {
   if test "$with_dynamic_modules" != no; then
-    set_dynamic_module_location
+    DESTDIR="$1"
+    set_dynamic_module_location ${DESTDIR}
     dyndir=${LIBDIR}/${DYNMOD}
     dll="lib"; for m in ${NEW_MODULES}; do dll=${dll}-$m; done; dll=${dll}@SHREXT@
     lib=${dyndir}/${dll}; libs="${NEW_LIBS} @CLISP_DEF@"; verbose @createsharedlib@
@@ -409,7 +413,7 @@ case "$1" in
           LOAD=${LOAD}' -i '"$moduledir/$f"
         done
         cd "$destinationdir"
-        prepare_dynamic_module
+        prepare_dynamic_module ""
         cd "$absolute_currentdir"
       done
       start_dir=`pwd`
@@ -554,7 +558,7 @@ case "$1" in
       cd "$moduledir"
       absolute_moduledir=`/bin/pwd`
       . ./link.sh
-      prepare_dynamic_module  # sets LIBDIR
+      prepare_dynamic_module "${DESTDIR}" # sets LIBDIR
       mkdir -p "${DESTDIR}${LIBDIR}/$moduledir"
       # when running "CLISP=./clisp ./clisp-link install <modname>"
       # in the build directory, avoid "cp: `...' and `...' are the same file"
