regenerated for rlimit/rusage changes

diff --git a/src/configure b/src/configure
--- a/src/configure
+++ b/src/configure
@@ -12780,6 +12780,89 @@ _ACEOF
 
 fi
 done
+
+for ac_func in getrlimit
+do
+as_ac_var=`echo "ac_cv_func_$ac_func" | $as_tr_sh`
+echo "$as_me:$LINENO: checking for $ac_func" >&5
+echo $ECHO_N "checking for $ac_func... $ECHO_C" >&6
+if eval "test \"\${$as_ac_var+set}\" = set"; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+/* System header to define __stub macros and hopefully few prototypes,
+    which can conflict with char $ac_func (); below.
+    Prefer <limits.h> to <assert.h> if __STDC__ is defined, since
+    <limits.h> exists even on freestanding compilers.  */
+#ifdef __STDC__
+# include <limits.h>
+#else
+# include <assert.h>
+#endif
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+{
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char $ac_func ();
+/* The GNU C library defines this for functions which it implements
+    to always fail with ENOSYS.  Some functions are actually named
+    something starting with __ and the normal name is an alias.  */
+#if defined (__stub_$ac_func) || defined (__stub___$ac_func)
+choke me
+#else
+char (*f) () = $ac_func;
+#endif
+#ifdef __cplusplus
+}
+#endif
+
+int
+main ()
+{
+return f != $ac_func;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  eval "$as_ac_var=yes"
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+eval "$as_ac_var=no"
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+fi
+echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_var'}'`" >&5
+echo "${ECHO_T}`eval echo '${'$as_ac_var'}'`" >&6
+if test `eval echo '${'$as_ac_var'}'` = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define `echo "HAVE_$ac_func" | $as_tr_cpp` 1
+_ACEOF
+
+fi
+done
 if test $ac_cv_func_setrlimit = yes; then
 echo "$as_me:$LINENO: checking for getrlimit declaration" >&5
 echo $ECHO_N "checking for getrlimit declaration... $ECHO_C" >&6
@@ -14211,27 +14294,33 @@ cat >>conftest.$ac_ext <<_ACEOF
 #include <stdio.h>
 #include <sys/types.h> /* NetBSD 1.0 needs this */
 #include <sys/time.h>
+#include <time.h> /* for time(2) */
 #include <sys/resource.h>
 int main ()
 {
   struct rusage used, prev;
+  time_t end = time(NULL)+1;
   int count = 0;
 
-  /* getrusage is defined but not do anything. */
-  if (!(getrusage(RUSAGE_SELF, &prev) == 0)) exit(1);
-  sleep (1);
-
-  while (++count < 10000)
-    {
-      getrusage(RUSAGE_SELF, &used);
-      if ((used.ru_utime.tv_usec != prev.ru_utime.tv_usec)
-          || (used.ru_utime.tv_sec != prev.ru_utime.tv_sec)
-          || (used.ru_stime.tv_usec != prev.ru_stime.tv_usec)
-          || (used.ru_stime.tv_sec != prev.ru_stime.tv_sec))
-        exit (0);
+  if ((count = getrusage(RUSAGE_SELF, &prev))) {
+    /* getrusage is defined but does not do anything. */
+    /*fprintf(stderr,"getrusage failed: return=%d\n",count);*/
+    return 1;
+  }
+  while (time(NULL) < end) {
+    count++;
+    getrusage(RUSAGE_SELF, &used);
+    if ((used.ru_utime.tv_usec != prev.ru_utime.tv_usec)
+        || (used.ru_utime.tv_sec != prev.ru_utime.tv_sec)
+        || (used.ru_stime.tv_usec != prev.ru_stime.tv_usec)
+        || (used.ru_stime.tv_sec != prev.ru_stime.tv_sec)) {
+      /*fprintf(stderr,"success after %d runs\n",count);*/
+      return 0;
     }
+  }
   /* getrusage is defined but does not work. */
-  exit (1);
+  /*fprintf(stderr,"failure after %d runs\n",count);*/
+  return 1;
 }
 _ACEOF
 rm -f conftest$ac_exeext
