regenerated

diff --git a/src/configure b/src/configure
--- a/src/configure
+++ b/src/configure
@@ -1011,7 +1011,11 @@ POSUB
 LIBSIGSEGV
 LTLIBSIGSEGV
 LIBAVCALL
+LTLIBAVCALL
+LIBAVCALL_PREFIX
 LIBCALLBACK
+LTLIBCALLBACK
+LIBCALLBACK_PREFIX
 XMKMF
 X_CFLAGS
 X_PRE_LIBS
@@ -1658,8 +1662,8 @@ Optional Packages:
   --with-libsigsegv-prefix[=DIR]  search for libsigsegv in DIR/include and DIR/lib
   --without-libsigsegv-prefix     don't search for libsigsegv in includedir and libdir
   --with-ffcall           use FFCALL (default is YES, if present)
-  --with-libffcall-prefix[=DIR]  search for libffcall in DIR/include and DIR/lib
-  --without-libffcall-prefix     don't search for libffcall in includedir and libdir
+  --with-libffcall-prefix[=DIR]  search for libavcall, libcallback in DIR/include and DIR/lib
+  --without-libffcall-prefix     don't search for libavcall, libcallback in includedir and libdir
   --with-lightning-prefix additional place to look for the lightning headers
   --with-x                use the X Window System
   --with-libtermcap-prefix=DIR  search for ncurses and termcap in DIR
@@ -6868,7 +6872,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 6871 "configure"' > conftest.$ac_ext
+  echo '#line 6875 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -9741,11 +9745,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:9744: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:9748: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:9748: \$? = $ac_status" >&5
+   echo "$as_me:9752: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -10031,11 +10035,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:10034: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:10038: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:10038: \$? = $ac_status" >&5
+   echo "$as_me:10042: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -10135,11 +10139,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:10138: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:10142: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:10142: \$? = $ac_status" >&5
+   echo "$as_me:10146: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -12499,7 +12503,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 12502 "configure"
+#line 12506 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12599,7 +12603,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 12602 "configure"
+#line 12606 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -15000,11 +15004,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15003: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15007: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:15007: \$? = $ac_status" >&5
+   echo "$as_me:15011: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -15104,11 +15108,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15107: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15111: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:15111: \$? = $ac_status" >&5
+   echo "$as_me:15115: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -16687,11 +16691,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16690: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16694: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16694: \$? = $ac_status" >&5
+   echo "$as_me:16698: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -16791,11 +16795,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16794: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16798: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:16798: \$? = $ac_status" >&5
+   echo "$as_me:16802: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -18998,11 +19002,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:19001: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:19005: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:19005: \$? = $ac_status" >&5
+   echo "$as_me:19009: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -19288,11 +19292,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:19291: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:19295: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:19295: \$? = $ac_status" >&5
+   echo "$as_me:19299: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -19392,11 +19396,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:19395: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:19399: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:19399: \$? = $ac_status" >&5
+   echo "$as_me:19403: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -27901,6 +27905,9 @@ fi
 
 
 
+
+
+
     use_additional=yes
 
   acl_save_prefix="$prefix"
@@ -27942,7 +27949,7 @@ if test "${with_libiconv_prefix+set}" = set; then
 
 fi
 
-  LIBICONV=
+      LIBICONV=
   LTLIBICONV=
   INCICONV=
   LIBICONV_PREFIX=
@@ -28331,6 +28338,11 @@ fi
       LTLIBICONV="${LTLIBICONV}${LTLIBICONV:+ }-R$found_dir"
     done
   fi
+
+
+
+
+
 
 
 
@@ -29530,6 +29542,9 @@ echo "${ECHO_T}$LIBICONV" >&6; }
 
 
 
+
+
+
     use_additional=yes
 
   acl_save_prefix="$prefix"
@@ -29571,7 +29586,7 @@ if test "${with_libintl_prefix+set}" = set; then
 
 fi
 
-  LIBINTL=
+      LIBINTL=
   LTLIBINTL=
   INCINTL=
   LIBINTL_PREFIX=
@@ -29961,6 +29976,11 @@ fi
     done
   fi
 
+
+
+
+
+
           { echo "$as_me:$LINENO: checking for GNU gettext in libintl" >&5
 echo $ECHO_N "checking for GNU gettext in libintl... $ECHO_C" >&6; }
 if { as_var=$gt_func_gnugettext_libintl; eval "test \"\${$as_var+set}\" = set"; }; then
@@ -30204,6 +30224,9 @@ _ACEOF
 
 
 
+
+
+
     use_additional=yes
 
   acl_save_prefix="$prefix"
@@ -30245,7 +30268,7 @@ if test "${with_libsigsegv_prefix+set}" = set; then
 
 fi
 
-  LIBSIGSEGV=
+      LIBSIGSEGV=
   LTLIBSIGSEGV=
   INCSIGSEGV=
   LIBSIGSEGV_PREFIX=
@@ -30636,6 +30659,11 @@ fi
   fi
 
 
+
+
+
+
+
         cl_save_CPPFLAGS="$CPPFLAGS"
 
   for element in $INCSIGSEGV; do
@@ -30745,6 +30773,42 @@ else
   cl_use_ffcall=default
 fi
 
+if test $cl_use_ffcall != no; then
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+  { echo "$as_me:$LINENO: checking how to link with libavcall" >&5
+echo $ECHO_N "checking how to link with libavcall... $ECHO_C" >&6; }
+if test "${ac_cv_libavcall_libs+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+
+
+
+
+
 
 
 
@@ -30788,17 +30852,8 @@ if test "${with_libffcall_prefix+set}" = set; then
     fi
 
 fi
-if test $cl_use_ffcall != no; then
- { echo "$as_me:$LINENO: checking whether ffcall is present" >&5
-echo $ECHO_N "checking whether ffcall is present... $ECHO_C" >&6; }
-if test "${cl_cv_have_ffcall+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-    cl_cv_have_ffcall=no
-  cl_save_CPPFLAGS="$CPPFLAGS"
-  cl_save_LIBS="$LIBS"
 
-  LIBAVCALL=
+      LIBAVCALL=
   LTLIBAVCALL=
   INCAVCALL=
   LIBAVCALL_PREFIX=
@@ -31189,6 +31244,23 @@ else
   fi
 
 
+
+
+
+
+    ac_cv_libavcall_libs="$LIBAVCALL"
+    ac_cv_libavcall_ltlibs="$LTLIBAVCALL"
+    ac_cv_libavcall_cppflags="$INCAVCALL"
+    ac_cv_libavcall_prefix="$LIBAVCALL_PREFIX"
+
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_libavcall_libs" >&5
+echo "${ECHO_T}$ac_cv_libavcall_libs" >&6; }
+  LIBAVCALL="$ac_cv_libavcall_libs"
+  LTLIBAVCALL="$ac_cv_libavcall_ltlibs"
+  INCAVCALL="$ac_cv_libavcall_cppflags"
+  LIBAVCALL_PREFIX="$ac_cv_libavcall_prefix"
+
   for element in $INCAVCALL; do
     haveit=
     for x in $CPPFLAGS; do
@@ -31212,30 +31284,72 @@ else
   done
 
 
-  for element in $LIBAVCALL; do
-    haveit=
-    for x in $LIBS; do
+
+
+      HAVE_LIBAVCALL=yes
+
+
+
+
+
+
+
+
+  { echo "$as_me:$LINENO: checking how to link with libcallback" >&5
+echo $ECHO_N "checking how to link with libcallback... $ECHO_C" >&6; }
+if test "${ac_cv_libcallback_libs+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+
+
+
+
+
+
+
+
+    use_additional=yes
 
   acl_save_prefix="$prefix"
   prefix="$acl_final_prefix"
   acl_save_exec_prefix="$exec_prefix"
   exec_prefix="$acl_final_exec_prefix"
-  eval x=\"$x\"
+
+    eval additional_includedir=\"$includedir\"
+    eval additional_libdir=\"$libdir\"
+
   exec_prefix="$acl_save_exec_prefix"
   prefix="$acl_save_prefix"
 
-      if test "X$x" = "X$element"; then
-        haveit=yes
-        break
+
+# Check whether --with-libffcall-prefix was given.
+if test "${with_libffcall_prefix+set}" = set; then
+  withval=$with_libffcall_prefix;
+    if test "X$withval" = "Xno"; then
+      use_additional=no
+    else
+      if test "X$withval" = "X"; then
+
+  acl_save_prefix="$prefix"
+  prefix="$acl_final_prefix"
+  acl_save_exec_prefix="$exec_prefix"
+  exec_prefix="$acl_final_exec_prefix"
+
+          eval additional_includedir=\"$includedir\"
+          eval additional_libdir=\"$libdir\"
+
+  exec_prefix="$acl_save_exec_prefix"
+  prefix="$acl_save_prefix"
+
+      else
+        additional_includedir="$withval/include"
+        additional_libdir="$withval/$acl_libdirstem"
       fi
-    done
-    if test -z "$haveit"; then
-      LIBS="${LIBS}${LIBS:+ }$element"
     fi
-  done
 
+fi
 
-  LIBCALLBACK=
+      LIBCALLBACK=
   LTLIBCALLBACK=
   INCCALLBACK=
   LIBCALLBACK_PREFIX=
@@ -31626,6 +31740,23 @@ else
   fi
 
 
+
+
+
+
+    ac_cv_libcallback_libs="$LIBCALLBACK"
+    ac_cv_libcallback_ltlibs="$LTLIBCALLBACK"
+    ac_cv_libcallback_cppflags="$INCCALLBACK"
+    ac_cv_libcallback_prefix="$LIBCALLBACK_PREFIX"
+
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_libcallback_libs" >&5
+echo "${ECHO_T}$ac_cv_libcallback_libs" >&6; }
+  LIBCALLBACK="$ac_cv_libcallback_libs"
+  LTLIBCALLBACK="$ac_cv_libcallback_ltlibs"
+  INCCALLBACK="$ac_cv_libcallback_cppflags"
+  LIBCALLBACK_PREFIX="$ac_cv_libcallback_prefix"
+
   for element in $INCCALLBACK; do
     haveit=
     for x in $CPPFLAGS; do
@@ -31645,6 +31776,36 @@ else
     done
     if test -z "$haveit"; then
       CPPFLAGS="${CPPFLAGS}${CPPFLAGS:+ }$element"
+    fi
+  done
+
+
+
+
+      HAVE_LIBCALLBACK=yes
+
+
+
+
+  for element in $LIBAVCALL; do
+    haveit=
+    for x in $LIBS; do
+
+  acl_save_prefix="$prefix"
+  prefix="$acl_final_prefix"
+  acl_save_exec_prefix="$exec_prefix"
+  exec_prefix="$acl_final_exec_prefix"
+  eval x=\"$x\"
+  exec_prefix="$acl_save_exec_prefix"
+  prefix="$acl_save_prefix"
+
+      if test "X$x" = "X$element"; then
+        haveit=yes
+        break
+      fi
+    done
+    if test -z "$haveit"; then
+      LIBS="${LIBS}${LIBS:+ }$element"
     fi
   done
 
@@ -31817,7 +31978,7 @@ fi
 
 done
 
-  { echo "$as_me:$LINENO: checking for library containing __builtin_avcall" >&5
+{ echo "$as_me:$LINENO: checking for library containing __builtin_avcall" >&5
 echo $ECHO_N "checking for library containing __builtin_avcall... $ECHO_C" >&6; }
 if test "${ac_cv_search___builtin_avcall+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -31900,7 +32061,7 @@ if test "$ac_res" != no; then
 
 fi
 
-  { echo "$as_me:$LINENO: checking for library containing trampoline_r_data0" >&5
+{ echo "$as_me:$LINENO: checking for library containing trampoline_r_data0" >&5
 echo $ECHO_N "checking for library containing trampoline_r_data0... $ECHO_C" >&6; }
 if test "${ac_cv_search_trampoline_r_data0+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -31983,26 +32144,16 @@ if test "$ac_res" != no; then
 
 fi
 
-  if test $ac_cv_header_avcall_h = yes \
-       -a $ac_cv_header_callback_h = yes \
-       -a "$ac_cv_search___builtin_avcall" != no \
-       -a "$ac_cv_search_trampoline_r_data0" != no
-  then cl_cv_have_ffcall=yes
-  else
-    CPPFLAGS="$cl_save_CPPFLAGS"
-    LIBS="$cl_save_LIBS"
-    LIBAVCALL=
-    LIBCALLBACK=
-  fi
-
+if test $ac_cv_header_avcall_h = yes \
+     -a $ac_cv_header_callback_h = yes \
+     -a "$ac_cv_search___builtin_avcall" != no \
+     -a "$ac_cv_search_trampoline_r_data0" != no
+then cl_have_ffcall=yes
+else cl_have_ffcall=no
 fi
-{ echo "$as_me:$LINENO: result: $cl_cv_have_ffcall" >&5
-echo "${ECHO_T}$cl_cv_have_ffcall" >&6; }
-
-
- if test $cl_use_ffcall = yes -a $cl_cv_have_ffcall = no; then
-   FFCALL=ffcall-1.8
-   { { echo "$as_me:$LINENO: error: despite --with-ffcall, FFCALL was not found
+if test $cl_use_ffcall = yes -a $cl_have_ffcall = no; then
+  FFCALL=ffcall-1.8
+  { { echo "$as_me:$LINENO: error: despite --with-ffcall, FFCALL was not found
  Either call configure without --with-ffcall or do
   mkdir tools; cd tools; prefix=\`pwd\`/${ac_cv_host}
   wget http://ftp.gnu.org/pub/gnu/ffcall/${FFCALL}.tar.gz
@@ -32021,7 +32172,7 @@ echo "$as_me: error: despite --with-ffcall, FFCALL was not found
   cd ../..
   ./configure --with-libffcall-prefix=\${prefix} $*" >&2;}
    { (exit 1); exit 1; }; }
- fi
+fi
 fi;
 
 # Check whether --with-lightning-prefix was given.
@@ -49997,6 +50148,9 @@ if test $ac_cv_search_tgetent != no ; then
 
 
 
+
+
+
     use_additional=yes
 
   acl_save_prefix="$prefix"
@@ -50038,7 +50192,7 @@ if test "${with_libreadline_prefix+set}" = set; then
 
 fi
 
-  LIBREADLINE=
+      LIBREADLINE=
   LTLIBREADLINE=
   INCREADLINE=
   LIBREADLINE_PREFIX=
@@ -50427,6 +50581,11 @@ fi
       LTLIBREADLINE="${LTLIBREADLINE}${LTLIBREADLINE:+ }-R$found_dir"
     done
   fi
+
+
+
+
+
 
  ac_save_CPPFLAGS="$CPPFLAGS"
  CPPFLAGS="$CPPFLAGS $INCREADLINE"
@@ -60663,7 +60822,11 @@ POSUB!$POSUB$ac_delim
 LIBSIGSEGV!$LIBSIGSEGV$ac_delim
 LTLIBSIGSEGV!$LTLIBSIGSEGV$ac_delim
 LIBAVCALL!$LIBAVCALL$ac_delim
+LTLIBAVCALL!$LTLIBAVCALL$ac_delim
+LIBAVCALL_PREFIX!$LIBAVCALL_PREFIX$ac_delim
 LIBCALLBACK!$LIBCALLBACK$ac_delim
+LTLIBCALLBACK!$LTLIBCALLBACK$ac_delim
+LIBCALLBACK_PREFIX!$LIBCALLBACK_PREFIX$ac_delim
 XMKMF!$XMKMF$ac_delim
 X_CFLAGS!$X_CFLAGS$ac_delim
 X_PRE_LIBS!$X_PRE_LIBS$ac_delim
@@ -60679,7 +60842,7 @@ gltests_LIBOBJS!$gltests_LIBOBJS$ac_delim
 gltests_LTLIBOBJS!$gltests_LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 55; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 59; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
