regenerated for the HAVE_READLINE <-- HAVE_READLINE_READLINE_H change

diff --git a/src/configure b/src/configure
--- a/src/configure
+++ b/src/configure
@@ -22178,52 +22178,6 @@ fi
 
 done
 
-  echo "$as_me:$LINENO: checking for rl_already_prompted" >&5
-echo $ECHO_N "checking for rl_already_prompted... $ECHO_C" >&6
-  cat >conftest.$ac_ext <<_ACEOF
-#line $LINENO "configure"
-#include "confdefs.h"
-
-#include <stdio.h>
-#include <readline/readline.h>
-
-#ifdef F77_DUMMY_MAIN
-#  ifdef __cplusplus
-     extern "C"
-#  endif
-   int F77_DUMMY_MAIN() { return 1; }
-#endif
-int
-main ()
-{
-rl_already_prompted = 1;
-  ;
-  return 0;
-}
-_ACEOF
-rm -f conftest.$ac_objext
-if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
-  (eval $ac_compile) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } &&
-         { ac_try='test -s conftest.$ac_objext'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; }; then
-  ac_cv_header_readline_readline_h=yes
-  echo "$as_me:$LINENO: result: yes" >&5
-echo "${ECHO_T}yes" >&6
-else
-  echo "$as_me: failed program was:" >&5
-cat conftest.$ac_ext >&5
-ac_cv_header_readline_readline_h=no
-  echo "$as_me:$LINENO: result: no; readline is too old and will not be used" >&5
-echo "${ECHO_T}no; readline is too old and will not be used" >&6
-fi
-rm -f conftest.$ac_objext conftest.$ac_ext
   if test $ac_cv_header_readline_readline_h = yes ; then
     echo "$as_me:$LINENO: checking for library containing readline" >&5
 echo $ECHO_N "checking for library containing readline... $ECHO_C" >&6
@@ -22481,14 +22435,62 @@ echo "$as_me:$LINENO: result: ${ac_t:-
 echo "${ECHO_T}${ac_t:-
          }$cl_cv_proto_rl_filename_completion_function" >&6
 
-      cat >>confdefs.h <<_ACEOF
+    cat >>confdefs.h <<_ACEOF
 #define READLINE_FILE_COMPLETE ${RL_FCF}
 _ACEOF
 
-      cat >>confdefs.h <<_ACEOF
+    cat >>confdefs.h <<_ACEOF
 #define READLINE_CONST $cl_cv_proto_readline_const
 _ACEOF
 
+    echo "$as_me:$LINENO: checking for rl_already_prompted" >&5
+echo $ECHO_N "checking for rl_already_prompted... $ECHO_C" >&6
+    cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+
+#include <stdio.h>
+#include <readline/readline.h>
+
+#ifdef F77_DUMMY_MAIN
+#  ifdef __cplusplus
+     extern "C"
+#  endif
+   int F77_DUMMY_MAIN() { return 1; }
+#endif
+int
+main ()
+{
+rl_already_prompted = 1;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+    cat >>confdefs.h <<\_ACEOF
+#define HAVE_READLINE 1
+_ACEOF
+
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+echo "$as_me:$LINENO: result: no; readline is too old and will not be used" >&5
+echo "${ECHO_T}no; readline is too old and will not be used" >&6
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
   fi
 fi
 
