regenerated

diff --git a/src/configure b/src/configure
--- a/src/configure
+++ b/src/configure
@@ -26959,7 +26959,7 @@ if test "$ac_x_libraries" = no; then
   # See if we find them without any special options.
   # Don't add to $LIBS permanently.
   ac_save_LIBS=$LIBS
-  LIBS="-lX11 $LIBS"
+  LIBS="-lXt $LIBS"
   cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
@@ -37020,7 +37020,7 @@ fi
 rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
 fi
 for y in 'caddr_t arg' 'void* arg' '...'; do
-for x in 'int' 'unsigned long' 'long'; do
+for x in 'unsigned int' 'int' 'unsigned long' 'long' 'size_t' 'socklen_t'; do
 if test -z "$have_ioctl"; then
 cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
@@ -37096,10 +37096,11 @@ fi
 done
 done
 if test -z "$have_ioctl"; then
-  echo "*** Missing autoconfiguration support for this platform." 1>&2
-  echo "*** Please report this as a bug to the CLISP developers." 1>&2
-  echo "*** When doing this, please also show your system's ioctl() declaration." 1>&2
-  exit 1
+{ { echo "$as_me:$LINENO: error: please report the ioctl() declaration on your platform to $PACKAGE_NAME developers at $PACKAGE_BUGREPORT
+See \`config.log' for more details." >&5
+echo "$as_me: error: please report the ioctl() declaration on your platform to $PACKAGE_NAME developers at $PACKAGE_BUGREPORT
+See \`config.log' for more details." >&2;}
+   { (exit 1); exit 1; }; }
 fi
 
 cl_cv_proto_ioctl="extern int ioctl ($cl_cv_proto_ioctl_args);"
@@ -37841,9 +37842,9 @@ if test "${cl_cv_proto_select+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
 
-for z in '' 'const'; do
+for z in '' 'const' '__const'; do
 for y in 'fd_set' 'int' 'void' 'struct fd_set'; do
-for x in 'int' 'size_t'; do
+for x in 'unsigned int' 'int' 'unsigned long' 'long' 'size_t' 'socklen_t'; do
 if test -z "$have_select"; then
 cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
@@ -37923,10 +37924,11 @@ done
 done
 done
 if test -z "$have_select"; then
-  echo "*** Missing autoconfiguration support for this platform." 1>&2
-  echo "*** Please report this as a bug to the CLISP developers." 1>&2
-  echo "*** When doing this, please also show your system's select() declaration." 1>&2
-  exit 1
+{ { echo "$as_me:$LINENO: error: please report the select() declaration on your platform to $PACKAGE_NAME developers at $PACKAGE_BUGREPORT
+See \`config.log' for more details." >&5
+echo "$as_me: error: please report the select() declaration on your platform to $PACKAGE_NAME developers at $PACKAGE_BUGREPORT
+See \`config.log' for more details." >&2;}
+   { (exit 1); exit 1; }; }
 fi
 
 cl_cv_proto_select="extern int select ($cl_cv_proto_select_arg1, $cl_cv_proto_select_arg2 *, $cl_cv_proto_select_arg2 *, $cl_cv_proto_select_arg2 *, $cl_cv_proto_select_arg5 struct timeval *);"
@@ -38861,9 +38863,9 @@ if test "${cl_cv_proto_connect+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
 
-for x in '' 'const'; do
+for x in '' 'const' '__const'; do
 for y in 'struct sockaddr *' 'void*'; do
-for z in 'int' 'size_t' 'socklen_t'; do
+for z in 'unsigned int' 'int' 'unsigned long' 'long' 'size_t' 'socklen_t'; do
 if test -z "$have_connect_decl"; then
 cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
@@ -38936,10 +38938,11 @@ done
 done
 done
 if test -z "$have_connect_decl"; then
-  echo "*** Missing autoconfiguration support for this platform." 1>&2
-  echo "*** Please report this as a bug to the CLISP developers." 1>&2
-  echo "*** When doing this, please also show your system's connect() declaration." 1>&2
-  exit 1
+{ { echo "$as_me:$LINENO: error: please report the connect() declaration on your platform to $PACKAGE_NAME developers at $PACKAGE_BUGREPORT
+See \`config.log' for more details." >&5
+echo "$as_me: error: please report the connect() declaration on your platform to $PACKAGE_NAME developers at $PACKAGE_BUGREPORT
+See \`config.log' for more details." >&2;}
+   { (exit 1); exit 1; }; }
 fi
 
 cl_cv_proto_connect="extern int connect (int, $cl_cv_proto_connect_arg2a $cl_cv_proto_connect_arg2b, $cl_cv_proto_connect_arg3);"
@@ -39651,8 +39654,8 @@ if test "${cl_cv_proto_inet_addr+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
 
-for x in '' 'const'; do
-for y in 'struct in_addr' 'unsigned long' 'unsigned int'; do
+for x in '' 'const' '__const'; do
+for y in 'unsigned int' 'int' 'unsigned long' 'long' 'size_t' 'socklen_t'; do
 if test -z "$have_inet_addr"; then
 cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
@@ -39730,10 +39733,11 @@ fi
 done
 done
 if test -z "$have_inet_addr"; then
-  echo "*** Missing autoconfiguration support for this platform." 1>&2
-  echo "*** Please report this as a bug to the CLISP developers." 1>&2
-  echo "*** When doing this, please also show your system's inet_addr() declaration." 1>&2
-  exit 1
+{ { echo "$as_me:$LINENO: error: please report the inet_addr() declaration on your platform to $PACKAGE_NAME developers at $PACKAGE_BUGREPORT
+See \`config.log' for more details." >&5
+echo "$as_me: error: please report the inet_addr() declaration on your platform to $PACKAGE_NAME developers at $PACKAGE_BUGREPORT
+See \`config.log' for more details." >&2;}
+   { (exit 1); exit 1; }; }
 fi
 
 cl_cv_proto_inet_addr="extern $cl_cv_proto_inet_addr_ret inet_addr ($cl_cv_proto_inet_addr_arg1 char*);"
@@ -39839,9 +39843,9 @@ if test "${cl_cv_proto_setsockopt+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
 
-for z in 'int' 'unsigned int' 'size_t'; do
+for z in 'unsigned int' 'int' 'unsigned long' 'long' 'size_t' 'socklen_t'; do
 for y in 'char*' 'void*'; do
-for x in '' 'const'; do
+for x in '' 'const' '__const'; do
 if test -z "$have_setsockopt_decl"; then
 cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
@@ -39911,10 +39915,11 @@ done
 done
 done
 if test -z "$have_setsockopt_decl"; then
-  echo "*** Missing autoconfiguration support for this platform." 1>&2
-  echo "*** Please report this as a bug to the CLISP developers." 1>&2
-  echo "*** When doing this, please also show your system's setsockopt() declaration." 1>&2
-  exit 1
+{ { echo "$as_me:$LINENO: error: please report the setsockopt() declaration on your platform to $PACKAGE_NAME developers at $PACKAGE_BUGREPORT
+See \`config.log' for more details." >&5
+echo "$as_me: error: please report the setsockopt() declaration on your platform to $PACKAGE_NAME developers at $PACKAGE_BUGREPORT
+See \`config.log' for more details." >&2;}
+   { (exit 1); exit 1; }; }
 fi
 
 cl_cv_proto_setsockopt="extern int setsockopt (int, int, int, $cl_cv_proto_setsockopt_const $cl_cv_proto_setsockopt_arg_t, $cl_cv_proto_setsockopt_optlen_t);"
