do not fail when the destination exists already (fail): new function

diff --git a/src/lndir b/src/lndir
--- a/src/lndir
+++ b/src/lndir
@@ -7,9 +7,13 @@
 # Abort in case something fails.
 set -e
 
+fail(){
+    echo "$*" 1>&2
+    exit 1
+}
+
 if test $# != 2; then
-  echo "Usage: $0 SRC DST" 1>&2
-  exit 1
+  fail "Usage: $0 SRC DST"
 fi
 
 SRC="$1"
@@ -20,6 +24,7 @@ DST="$2"
 # system supports that, else file copy.
 link () {
 # Note: With some versions of "ln" this does not work if FILE2 is a symlink.
+rm -f "$2";
 if ln "$1" "$2" 2>/dev/null; then
   :
 else
@@ -41,7 +46,7 @@ fi
 mkdirparent () {
 DIR="$1"
 DIR=`echo "$DIR" | sed -e 's,/*$,,'`
-defaultIFS=' 	
+defaultIFS='
 '
 IFS="${IFS-${defaultIFS}}"
 oIFS="${IFS}"
@@ -60,19 +65,18 @@ done
 if test -r "$SRC"; then
   :
 else
-  echo "$0: source does not exist: $SRC" 1>&2
-  exit 1
+  fail "$0: source does not exist: $SRC"
 fi
 
-if test -r "$DST"; then
-  echo "$0: destination already exists: $DST" 1>&2
-  exit 1
-fi
+#if test -r "$DST"; then
+#  fail "$0: destination already exists: $DST"
+#fi
 
 mkdirparent "$DST"
 
 for f in `cd "$SRC" ; find . -type d -print`; do
-  mkdir "$DST"`echo "$f" | sed -e 's,^\.,,'`
+  dir="$DST"`echo "$f" | sed -e 's,^\.,,'`;
+  test -d ${dir} || mkdir ${dir};
 done
 
 for f in `cd "$SRC" ; find . -type f -print`; do
