Remove useless trailing semicolons. They are just confusing.

diff --git a/src/makemake.in b/src/makemake.in
--- a/src/makemake.in
+++ b/src/makemake.in
@@ -6,7 +6,7 @@
 # Simple usage:
 #        ./makemake [--with-PACKAGE] [debug] > Makefile
 
-HSDEFAULT="http://www.lisp.org/HyperSpec/";
+HSDEFAULT="http://www.lisp.org/HyperSpec/"
 hyperspec=${CLHSROOT:-${HSDEFAULT}}
 
 info_help () {
@@ -128,9 +128,9 @@ ECHOVAL_END
 fi
 
 link_dep() {
-  echol "$1 : $2";
+  echol "$1 : $2"
   echotab "-\$(RM) $1"
-  echotab "-\$(LN_S) ${3-$2} $1";
+  echotab "-\$(LN_S) ${3-$2} $1"
   echol
 }
 
@@ -177,17 +177,17 @@ else
   tolower="tr A-Z a-z"
 fi
 my_eval(){
-  eval "$*";
+  eval "$*"
   if [ "${verbose}" = true -o "${verbose}" = yes ]; then echo "$*" >&2; fi
 }
 
-verbose=${CLISP_MAKEMAKE_VERBOSE:-false};
+verbose=${CLISP_MAKEMAKE_VERBOSE:-false}
 # Handle --with-... arguments
 while test -z "$endofargs"; do
   case "$1" in
     -verb* | --verb* )
-      verbose=`echol "$1"|sed 's/-*v[^=]*=*//'`;
-      test -n "${verbose}" || verbose=true;
+      verbose=`echol "$1"|sed 's/-*v[^=]*=*//'`
+      test -n "${verbose}" || verbose=true
       shift
       ;;
     -with-module=* | --with-module=*)
@@ -211,11 +211,11 @@ while test -z "$endofargs"; do
     -with-* | --with-*)
       package=`echol "$1"|sed 's/-*with-//'`
       packopt=`echol "${package}" | sed -e 's/^.*=\(.*\)$/\1/'`
-      if test -z "${packopt}"; then packopt=1;
-      elif [ "${packopt}" = "on" ];  then packopt=1;
-      elif [ "${packopt}" = "off" ]; then packopt=;
-      elif [ "${packopt}" = "yes" ]; then packopt=1;
-      elif [ "${packopt}" = "no" ];  then packopt=;
+      if test -z "${packopt}"; then packopt=1
+      elif [ "${packopt}" = "on" ];  then packopt=1
+      elif [ "${packopt}" = "off" ]; then packopt=
+      elif [ "${packopt}" = "yes" ]; then packopt=1
+      elif [ "${packopt}" = "no" ];  then packopt=
       fi
       package=`echol "${package}" | sed -e 's/=.*//'`
       # Delete all the valid chars; see if any are left.
@@ -522,7 +522,7 @@ BENCHDIR=benchmarks
 # Main host OS dependencies:
 
 # DOS-style filenames and file utilities
-H_DOS="false";
+H_DOS="false"
 if [ $HOS = os2 ]; then H_DOS="true"; fi
 if [ $HOS = win32 -a $HSYS != win32gcc ]; then H_DOS="true"; fi
 
@@ -600,9 +600,11 @@ else
   NEXT_M="$NEXT_"
 fi
 # maybe convert the cygwin cygdrive pathnames
-if [ ${HSYS} != win32gcc ]; then PWDCMD='`pwd`';
-else DEVPREFIX=`(cd c:; pwd | sed 's,^/\([a-z]*\)/.*,\1,')`;
-  PWDCMD='`pwd|sed '"'s,^/${DEVPREFIX}/\\(.\\),\1:,'"'`';
+if [ ${HSYS} != win32gcc ]; then
+  PWDCMD='`pwd`'
+else
+  DEVPREFIX=`(cd c:; pwd | sed 's,^/\([a-z]*\)/.*,\1,')`
+  PWDCMD='`pwd|sed '"'s,^/${DEVPREFIX}/\\(.\\),\1:,'"'`'
 fi
 HERE_='`pwd`'"${NEXT_}"
 
@@ -944,7 +946,7 @@ if [ $XCC_GCC = true ] ; then
     esac
   fi # DEBUGGING
   if [ $TSYS = win32gcc ] ; then
-    XCFLAGS=$XCFLAGS' -D_WIN32';
+    XCFLAGS=$XCFLAGS' -D_WIN32'
   fi
   if [ $TSYS = sun4 -o $TSYS = acorn ] ; then
     XCLFLAGS='-static'
@@ -956,7 +958,7 @@ if [ $XCC_GCC = true ] ; then
   XCC_NOOPTFLAGS=' -O0'
 
   if [ "${with_threads}" = "POSIX_THREADS" ]; then
-    XCFLAGS=${XCFLAGS}" -pthread";
+    XCFLAGS=${XCFLAGS}" -pthread"
   fi
 
 else
@@ -1155,7 +1157,7 @@ if [ "$DEBUGGING" = debug ] ; then
   elif [ ${HSYS} != "win32msvc" ]; then
     XCFLAGS=$XCFLAGS' -g'
   fi
-  XCFLAGS=$XCFLAGS' -DDEBUG_OS_ERROR -DDEBUG_SPVW -DSAFETY=3';
+  XCFLAGS=$XCFLAGS' -DDEBUG_OS_ERROR -DDEBUG_SPVW -DSAFETY=3'
   case "$CC" in
     *"g++"* ) XCFLAGS=$XCFLAGS' -DDEBUG_GCSAFETY -DNO_TYPECODES'; ;;
   esac
@@ -1266,7 +1268,7 @@ fi
 
 if [ "${with_termcap_ncurses}" = "0" -o "${LIBTERMCAP}" = "broken" ] ; then
   XCFLAGS=$XCFLAGS' -DNO_TERMCAP_NCURSES'
-  LIBTERMCAP="";
+  LIBTERMCAP=""
 fi
 
 # the type of library naming
@@ -1315,8 +1317,8 @@ if [ $TOS = unix -o $TOS = os2 ] ; then
     if [ "${with_readline}" != "" ]; then
       # --with-readline was supplied ==> barf when readline is missing
       if grep "#undef HAVE_READLINE" unixconf.h 2>&1 >/dev/null; then
-        echol "makemake: configure failed to detect readline" >&2;
-        exit 1;
+        echol "makemake: configure failed to detect readline" >&2
+        exit 1
       fi
     fi
   fi
@@ -1372,7 +1374,7 @@ if [ $TSYS = master -o $TOS = acorn ] ; then
   CPARTS=$CPARTS' acornaux acornsig'
 fi
 if [ -n "${with_threads}" -a "${with_threads}" != "0" ]; then
-  CPARTS=$CPARTS' zthread';
+  CPARTS=$CPARTS' zthread'
 fi
 
 EVERY_INCLUDES='lispbibl fsubr subr pseudofun constsym constobj '$OS_INCLUDES
@@ -1385,12 +1387,12 @@ done
 EVERY_INCLUDES_H=''
 if [ $TOS = unix ] ; then
   if [ -n '@STDBOOL_H@' -o -n '@STDINT_H@' ]; then
-    EVERY_INCLUDES_H=${EVERY_INCLUDES_H}' @STDBOOL_H@ @STDINT_H@';
-    XCFLAGS=${XCFLAGS}' -I.';
+    EVERY_INCLUDES_H=${EVERY_INCLUDES_H}' @STDBOOL_H@ @STDINT_H@'
+    XCFLAGS=${XCFLAGS}' -I.'
   fi
 else
   EVERY_INCLUDES_H=$EVERY_INCLUDES_H' stdbool.h stdint.h'
-  XCFLAGS=${XCFLAGS}' -I.';
+  XCFLAGS=${XCFLAGS}' -I.'
 fi
 if [ -n "$USE_LIBCHARSET" ] ; then
   EVERY_INCLUDES_H=$EVERY_INCLUDES_H' libcharset.h'
@@ -1404,10 +1406,10 @@ fi
 SPVW_INCLUDES=' spvw_module spvw_debug spvw_alloca spvw_mmap spvw_multimap spvw_singlemap spvw_page spvw_heap spvw_global spvw_gcstat spvw_space spvw_mark spvw_objsize spvw_update spvw_fault spvw_sigsegv spvw_sigcld spvw_sigpipe spvw_sigint spvw_sigwinch spvw_garcol spvw_genera1 spvw_genera2 spvw_genera3 spvw_allocate spvw_typealloc spvw_circ spvw_walk spvw_ctype spvw_language spvw_memfile'
 
 UNICODE_INCLUDES=''
-UNICODE_EXTRA='';
+UNICODE_EXTRA=''
 if [ "${with_unicode}" != "0" ] ; then
   UNICODE_INCLUDES=$UNICODE_INCLUDES' uni_upcase uni_downcase uni_attribute uniname'
-  UNICODE_EXTRA=${UNICODE_EXTRA}' streq.h cjk.h uniwidth.h width.c unitypes.h uniname.h uninames.h';
+  UNICODE_EXTRA=${UNICODE_EXTRA}' streq.h cjk.h uniwidth.h width.c unitypes.h uniname.h uninames.h'
 fi
 
 NLS_INCLUDES=''
@@ -1533,7 +1535,7 @@ LPARTS=$LPARTS' disassem condition loadform gstream xcharin keyboard'
 LPARTS=$LPARTS' screen beossock runprog query reploop dribble complete'
 LPARTS=$LPARTS' pprint describe room edit macros3 clhs inspect gray'
 if [ -n "${with_threads}" -a "${with_threads}" != "0" ]; then
-  LPARTS=$LPARTS' threads';
+  LPARTS=$LPARTS' threads'
 fi
 if [ $TSYS = master -o -n "$with_dynamic_ffi" ] ; then
   LPARTS=$LPARTS' foreign1'
@@ -2121,14 +2123,14 @@ fi
 LUTILS=''
 LUTILS=$LUTILS' modprep'
 
-PARAMS="intparam floatparam";
-PARAMS_H="";
+PARAMS="intparam floatparam"
+PARAMS_H=""
 line="init :"
 for parf in ${PARAMS}; do
   if [ ${TOS} != win32 ] ; then
-    line=$line" "${parf}.h;
+    line=$line" "${parf}.h
   fi
-  PARAMS_H=${PARAMS_H}" "${parf}.h;
+  PARAMS_H=${PARAMS_H}" "${parf}.h
 done
 if [ $XCC_UNUSABLE_CPP = true ] ; then
   line=$line" ${SRCTOPDIR}utils/gcc-cccp/cccp${HEXE}"
@@ -2390,7 +2392,7 @@ for f in $CPARTS genclisph modules $EXTRA_CPARTS ; do
   fi
   if [ $f = charstrg -a "${with_unicode}" != "0" ] ; then
     depends=$depends${UNICODE_INCLUDES}
-    dependsc=${dependsc}${UNICODE_EXTRA};
+    dependsc=${dependsc}${UNICODE_EXTRA}
   fi
   if [ $f = encoding ] ; then
     depends=$depends''$NLS_INCLUDES
@@ -2535,7 +2537,7 @@ done
 
 if [ $HOS = unix -o $HSYS = win32gcc ] ; then
   # on w32 -g, using lisp.o leads to a crash on the first statement in main()
-  test $HSYSOS = win32gcc -o $HSYSOS = cygwin; no_lisp_o=$?;
+  test $HSYSOS = win32gcc -o $HSYSOS = cygwin; no_lisp_o=$?
   echol "lisp.a : \$(OBJECTS)"
   if [ $no_lisp_o = 1 ]; then
     echotab "ld -r -o lisp.o \$(OBJECTS)"
@@ -2544,7 +2546,8 @@ if [ $HOS = unix -o $HSYS = win32gcc ] ; then
   if test -z "$LIBGCC"; then
     if [ $no_lisp_o = 1 ]; then
       echotab "\$(AR) rcv lisp.a lisp.o"
-    else echotab "\$(AR) rcv lisp.a \$(OBJECTS)"
+    else
+      echotab "\$(AR) rcv lisp.a \$(OBJECTS)"
     fi
   else
     # Test for libgcc.a because NeXT cc does not have it.
@@ -2741,10 +2744,11 @@ else
 fi
 if [ "${with_unicode}" != "0" ] ; then
   encflags=' -Efile UTF-8 -Eterminal UTF-8'
-else encflags=''
+else
+  encflags=''
 fi
-echol "RUN= ${HERE}lisp${LEXE} ${localeflags}${encflags} -norc";
-echol;
+echol "RUN= ${HERE}lisp${LEXE} ${localeflags}${encflags} -norc"
+echol
 
 for f in ${LUTILS} ; do
   echol "${f}.fas : ${UTILDIR_M}${f}.lisp lisp${LEXE} lispinit.mem"
@@ -2780,8 +2784,11 @@ fi
 if [ $CROSS = false ] ; then
 
   for f in $LPARTS ; do
-    if [ $f = "compiler" ]; then image=${interpreted}.mem;
-    else image=${halfcompiled}.mem; fi
+    if [ $f = "compiler" ]; then
+      image=${interpreted}.mem
+    else
+      image=${halfcompiled}.mem
+    fi
     echol "${f}.fas : ${f}.lisp lisp${LEXE} $image"
     # The strict minimum needed for compiling compiler.lisp is between 750KW
     # and 800KW. To reduce GCs, we spend 20% more than this.
@@ -2865,16 +2872,17 @@ if [ $CROSS = false ] ; then
   echol "test : lispinit.mem ${TESTDIR} \$(TESTLISPFILES) \$(TESTFASFILES)"
   if [ $HOS = unix -o $HSYS = win32gcc ] ; then
     # replace GENSYMs with a string
-    SEDRE='s/\(#Y([-a-zA-Z:]\{1,\}\)[0-9]\{2,\}\(-*[0-9]*\)/\1<GENSYM>\2/g';
-    FAIL=' || (echo "Test failed." ; exit 1)';
+    SEDRE='s/\(#Y([-a-zA-Z:]\{1,\}\)[0-9]\{2,\}\(-*[0-9]*\)/\1<GENSYM>\2/g'
+    FAIL=' || (echo "Test failed." ; exit 1)'
     for f in $LPARTS ; do
       # add the lisp files with GENSYMS in FLET here
       if [ ${f} = "threads" ]; then
-        echotab "sed '${SEDRE}' ${f}.fas > ${f}.fas1";
-        echotab "sed '${SEDRE}' ${TESTDIR}/${f}.fas > ${TESTDIR}/${f}.fas1";
-        echotab "cmp -s ${f}.fas1 ${TESTDIR}/${f}.fas1 ${FAIL}";
-        echotab "${RM} ${f}.fas1 ${TESTDIR}/${f}.fas1";
-      else echotab "cmp -s ${f}.fas ${TESTDIR}/${f}.fas ${FAIL}";
+        echotab "sed '${SEDRE}' ${f}.fas > ${f}.fas1"
+        echotab "sed '${SEDRE}' ${TESTDIR}/${f}.fas > ${TESTDIR}/${f}.fas1"
+        echotab "cmp -s ${f}.fas1 ${TESTDIR}/${f}.fas1 ${FAIL}"
+        echotab "${RM} ${f}.fas1 ${TESTDIR}/${f}.fas1"
+      else
+        echotab "cmp -s ${f}.fas ${TESTDIR}/${f}.fas ${FAIL}"
       fi
     done
     echotab 'echo "Test passed."'
@@ -2907,14 +2915,14 @@ if [ $CROSS = false ] ; then
   # have to reset *GENSYM-COUNTER* in the test image since the compiled
   # files can (and some actually do, like threads.lisp) contain GENSYMed
   # FLET locals, whose names are written to the FAS files
-  TESTIMAGE="${TESTDIR}${NEXT_M}testinit.mem";
-  echol "${TESTIMAGE}: lispinit.mem";
+  TESTIMAGE="${TESTDIR}${NEXT_M}testinit.mem"
+  echol "${TESTIMAGE}: lispinit.mem"
   # this does not help, unfortunately, since the number of GENSYM calls
   # depends on which files went into halfcompiled.mem as FAS files
-  #  echotab "\$(RUN) -M lispinit.mem -x \"(setq *gensym-counter* (- \`\$(RUN) -q -M ${halfcompiled}.mem -x '*gensym-counter*'\` 16)) (sys::%saveinitmem) (exit)\"";
-  #  echotab "\$(MV) lispimag.mem ${TESTIMAGE}";
-  echotab "\$(CP) lispinit.mem ${TESTIMAGE}";
-  echol;
+  #  echotab "\$(RUN) -M lispinit.mem -x \"(setq *gensym-counter* (- \`\$(RUN) -q -M ${halfcompiled}.mem -x '*gensym-counter*'\` 16)) (sys::%saveinitmem) (exit)\""
+  #  echotab "\$(MV) lispimag.mem ${TESTIMAGE}"
+  echotab "\$(CP) lispinit.mem ${TESTIMAGE}"
+  echol
 
   for f in $LPARTS ; do
     echol "${TESTDIR}${NEXT_M}${f}.fas : ${TESTDIR}${NEXT_M}${f}.lisp lisp${LEXE} ${TESTIMAGE}"
@@ -2986,9 +2994,10 @@ echotab_to_HEXE "\$(CC) \$(CFLAGS) \$(CLFLAGS) -DUSE_CLISP_H=1" "clisp-test.c" "
 echotab_to_HEXE "\$(CC) \$(CFLAGS) \$(CLFLAGS) -DUSE_CLISP_H=0" "clisp-test.c" "clisp-test-lispbibl"
 echotab "${HERE}clisp-test-clisp > clisp-test-clisp.out"
 echotab "${HERE}clisp-test-lispbibl > clisp-test-lispbibl.out"
-if [ $HOS = unix -o $HSYS = win32gcc ];
-then echotab  "cmp clisp-test-clisp.out clisp-test-lispbibl.out"
-else echotab "comp clisp-test-clisp.out clisp-test-lispbibl.out"
+if [ $HOS = unix -o $HSYS = win32gcc ]; then
+  echotab  "cmp clisp-test-clisp.out clisp-test-lispbibl.out"
+else
+  echotab "comp clisp-test-clisp.out clisp-test-lispbibl.out"
 fi
 echotab "\$(RM) genclisph${HEXE} clisp-test-clisp${HEXE} clisp-test-lispbibl${HEXE} clisp-test-clisp.out clisp-test-lispbibl.out"
 echol
@@ -3036,8 +3045,8 @@ echotab "\$(RMRF) full"
 echotab "CLISP_LINKKIT=. ${HERE}clisp-link add-module-sets base full \$(MODULES) || (\$(RMRF) full ; exit 1)"
 echol
 echol "full-check : full clisp"
-echotab "for m in \$(MODULES); do \$(RM) $$m/*.erg; done;"
-echotab 'z=""; for m in $(MODULES); do z=$$z" \""$$m/\"; done; ./clisp -norc -K full -C -i suite/tests -x "(run-some-tests '"'"'($$z))"';
+echotab "for m in \$(MODULES); do \$(RM) $$m/*.erg; done"
+echotab 'z=""; for m in $(MODULES); do z=$$z" \""$$m/\"; done; ./clisp -norc -K full -C -i suite/tests -x "(run-some-tests '"'"'($$z))"'
 echol
 OBSOLETE=$OBSOLETE" genclisph${HEXE}"
 
@@ -3047,9 +3056,9 @@ else
   manual_dvi=''
 fi
 echol "READMES = ANNOUNCE COPYRIGHT GNU-GPL SUMMARY NEWS README README.de README.es"`if [ $TOS = unix ] ; then echol ' MAGIC.add' ; fi``if [ ${HSYSOS} = cygwin ]; then echol ' cygwin.README'; fi`
-IMPNOTES_FILES="impnotes.html impnotes.css clisp.png";
+IMPNOTES_FILES="impnotes.html impnotes.css clisp.png"
 if [ ${HOS} = win32 ]; then
-  IMPNOTES_FILES=${IMPNOTES_FILES}" clisp.ico";
+  IMPNOTES_FILES=${IMPNOTES_FILES}" clisp.ico"
 fi
 echol "IMPNOTES = ${IMPNOTES_FILES}"
 echol "MANUALS = clisp.1 clisp.html \$(TXTFILES) \$(IMPNOTES)"
@@ -3059,7 +3068,7 @@ for f in ${IMPNOTES_FILES} ; do
   echotab "\$(LN_S) ${DOCDIR_M}${f} ${f}"
   echol
 done
-EMACS_FILES="clisp-coding.el clisp-indent.el clisp-indent.lisp";
+EMACS_FILES="clisp-coding.el clisp-indent.el clisp-indent.lisp"
 
 # On Unix, clisp.dvi & clisp.ps must be built by "make all", because
 # "make install" needs it and "make install" must not create files in
@@ -3093,7 +3102,8 @@ if [ -n "${SRCDIR}" ] ; then
     echol "${f} : ${SRCDIR}${f}"
     if [ $f = .gdbinit -a $LEXE != ".run" ]; then
       echotab "sed 's/lisp.run/lisp$LEXE/g' ${SRCDIR}${f} > ${f}"
-    else echotab "-\$(LN_S) ${SRCDIR}${f} ${f}"
+    else
+      echotab "-\$(LN_S) ${SRCDIR}${f} ${f}"
     fi
     echol
   done
@@ -3177,10 +3187,10 @@ done
 echol
 
 if [ $CROSS = false ] ; then
-  DRIVER_DEP=''; DRIVER_RES='';
+  DRIVER_DEP=''; DRIVER_RES=''
   if [ $HOS = win32 ]; then
-    DRIVER_RES=' clispres.o';
-    DRIVER_DEP=${DRIVER_RES}' w32shell.c';
+    DRIVER_RES=' clispres.o'
+    DRIVER_DEP=${DRIVER_RES}' w32shell.c'
     echol "clispres.o : clisp.rc"
     echotab "windres -i clisp.rc -o clispres.o"
     echol
@@ -3315,7 +3325,8 @@ if [ $CROSS = false ] ; then
     if [ ${HSYSOS} = cygwin ]; then
       echotab "\$(RM) \$(DESTDIR)\$(docdir)/Cygwin/clisp-\`cat VERSION\`.README"
       echotab "\$(RM) \$(DESTDIR)\$(bindir)/clisp.exe"
-    else echotab "\$(RM) \$(DESTDIR)\$(bindir)/clisp"
+    else
+      echotab "\$(RM) \$(DESTDIR)\$(bindir)/clisp"
     fi
     if [ -n "$USE_GETTEXT" ] ; then
       echotab "cd po && \$(MAKE) uninstall prefix='\$(DESTDIR)\$(prefix)' exec_prefix='\$(DESTDIR)\$(exec_prefix)'"
@@ -3393,10 +3404,10 @@ if [ ${HSYSOS} = cygwin ]; then
   echotab "echo '' >> cygwin.README"
   echotab "cat SUMMARY >> cygwin.README"
   echol
-  CLISP_VERSION="clisp-\`cat VERSION\`";
-  CLISP_SCRIPT=${CLISP_VERSION}-1.sh;
-  CLISP_CYGWIN=${CLISP_VERSION}-cygwin-`uname -r|sed 's/(.*)//g'`.tar.bz2;
-  echol "DEST_TMP='`pwd`/.install'";
+  CLISP_VERSION="clisp-\`cat VERSION\`"
+  CLISP_SCRIPT=${CLISP_VERSION}-1.sh
+  CLISP_CYGWIN=${CLISP_VERSION}-cygwin-`uname -r|sed 's/(.*)//g'`.tar.bz2
+  echol "DEST_TMP='`pwd`/.install'"
   echol "distrib : setup.hint cygwin.README force"
   echotab "\$(RMRF) \$(DEST_TMP); mkdir -p \$(DEST_TMP)"
   echotab "\$(MAKE) install prefix=/usr DESTDIR=\$(DEST_TMP)"
@@ -3465,7 +3476,7 @@ else
 fi
 echol
 echol "# Distribution file"
-PROC=`((uname -p) 2>/dev/null || mach 2>/dev/null) | $tolower`;
+PROC=`((uname -p) 2>/dev/null || mach 2>/dev/null) | $tolower`
 echol "DISTFILE=\$(PACKDIR)/\$(TOPDIR)-${HSYS:-unknown}-${PROC:-unknown}-${HSYSOS:-unknown}-`uname -r|sed 's/(.*)//g'`\$(PACKEXT)"
 echol
 needs='all'
@@ -3708,7 +3719,7 @@ if [ -n "${SRCDIR}" ] ; then
   line="$line modules.h"${UNICODE_EXTRA}
   line="$line \$(LISPFILES) NEWS clisp.png"
   if [ ${HOS} = win32 ]; then
-    line="$line clisp.ico";
+    line="$line clisp.ico"
   fi
   echotab "$line"
   if [ $HOS = unix -a $CROSS = false ] ; then
