regenerated

diff --git a/modules/berkeley-db/configure b/modules/berkeley-db/configure
--- a/modules/berkeley-db/configure
+++ b/modules/berkeley-db/configure
@@ -3942,6 +3942,123 @@ if test "$ac_cv_search_db_env_create" = "no"; then
 echo "$as_me: error: cannot find Berkeley-DB library" >&2;}
    { (exit 1); exit 1; }; }
 fi
+echo "$as_me:$LINENO: checking for DB_ENV.get_home" >&5
+echo $ECHO_N "checking for DB_ENV.get_home... $ECHO_C" >&6
+if test "${ac_cv_member_DB_ENV_get_home+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <db.h>
+
+int
+main ()
+{
+static DB_ENV ac_aggr;
+if (ac_aggr.get_home)
+return 0;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_member_DB_ENV_get_home=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <db.h>
+
+int
+main ()
+{
+static DB_ENV ac_aggr;
+if (sizeof ac_aggr.get_home)
+return 0;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_member_DB_ENV_get_home=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_member_DB_ENV_get_home=no
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
+echo "$as_me:$LINENO: result: $ac_cv_member_DB_ENV_get_home" >&5
+echo "${ECHO_T}$ac_cv_member_DB_ENV_get_home" >&6
+if test $ac_cv_member_DB_ENV_get_home = yes; then
+
+cat >>confdefs.h <<_ACEOF
+#define HAVE_DB_ENV_GET_HOME 1
+_ACEOF
+
+
+fi
+
+if test "$ac_cv_member_DB_ENV_get_home" = "no"; then
+  { { echo "$as_me:$LINENO: error: Berkeley-DB version 4.2 or better is requiired" >&5
+echo "$as_me: error: Berkeley-DB version 4.2 or better is requiired" >&2;}
+   { (exit 1); exit 1; }; }
+fi
 
 
 
diff --git a/modules/postgresql/configure b/modules/postgresql/configure
--- a/modules/postgresql/configure
+++ b/modules/postgresql/configure
@@ -3893,9 +3893,9 @@ _ACEOF
 fi
 done
 
-if test "$ac_cv_search_PQserverVersion" = "no"; then
-  { { echo "$as_me:$LINENO: error: PostgreSQL version 8 is required" >&5
-echo "$as_me: error: PostgreSQL version 8 is required" >&2;}
+if test "$ac_cv_func_PQserverVersion" = "no"; then
+  { { echo "$as_me:$LINENO: error: PostgreSQL version 8.0 or better is required" >&5
+echo "$as_me: error: PostgreSQL version 8.0 or better is required" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
